#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
mock-data.js 의 portfolio 섹션을 새 데이터로 교체하는 스크립트
"""

import re

FILE_PATH = r'C:\Users\CM\seul21\redevelopment\assets\data\mock-data.js'

NEW_PORTFOLIO = r"""  /* ──────────────────────────── 업무실적 ──────────────────────────── */
  portfolio: [
    { id:'pf1', name:'가락현대5차 소규모재건축 정비사업', type:'소규모정비', district:'송파구', status:'진행중', year:'2026', scale:'179세대',
      role:'정비사업 전과정 자문',
      description:'서울 송파구 가락동 161-3번지 일대 기존 노후 아파트를 지하 3층~지상 25층 4동 179세대로 재건축하는 소규모재건축 사업. 포스코이앤씨가 시공하며 공사비 738억원 규모이다. 조합설립인가(2020.04.28), 사업시행계획인가(2022.01.18), 착공(2023.02.23)을 거쳐 공정률 100%를 달성하였으며 2026년 5월 입주 예정이다. 당사는 기본계획 수립부터 착공·준공에 이르는 전 과정을 자문하였다.',
      featured:true,
      thumbnail:'../assets/images/portfolio/garak5.jpg', featuredImage:'../assets/images/portfolio/garak5.jpg',
      detailImage:'../assets/images/portfolio/garak5.jpg', imageAlt:'가락현대5차 소규모재건축 조감도',
      floorInfo:'지하3층 / 지상25층', floorAbove:25, floorBelow:3,
      grossFloorArea:'약 22,000㎡', floorAreaRatio:'249.9%',
      members:'145명', memberCount:145,
      siteArea:'약 7,400㎡', buildingArea:'약 2,800㎡', constructor:'포스코이앤씨', client:'가락현대5차소규모재건축조합',
      phase:'준공 예정 (2026.05)', totalCost:'약 738억원', proportionalRate:null,
      tasks:['기본계획 수립 자문','정비계획 수립 자문','안전진단 절차 자문','조합설립 업무 자문','사업시행계획 인허가 자문','시공사 선정 자문','착공 단계 시공관리 자문','준공 절차 자문','입주 및 이전등기 절차 자문','사업성 분석 자문'],
      issues:['공정률 100% 달성 — 2026년 5월 입주 예정','소규모재건축 특례 적용 (25층 허용)','포스코이앤씨 시공 — 공사비 738억원 규모','사전점검 및 입주 절차 진행 중'] },
    { id:'pf2', name:'반포124주구 재건축 정비사업', type:'재건축', district:'서초구', status:'진행중', year:'2026', scale:'5,007세대',
      role:'공공관리 및 사업성분석 자문',
      description:'서울 서초구 반포동 810번지 일대 370,484㎡ 부지에 추진되는 대규모 재건축 사업. 5,007세대 규모이며 현대건설이 시공을 맡고 있다. 추진위원회 승인(2011.12.28), 조합설립인가(2013.09.10), 사업시행인가(2017.09.27)를 거쳐 현재 관리처분계획 변경을 추진 중이다(2026.02.12). 당사는 공공관리 단계 조합설립추진위원회 승인업무 및 사업성분석업무를 자문하였다.',
      featured:true,
      thumbnail:'../assets/images/portfolio/banpo124.jpg', featuredImage:'../assets/images/portfolio/banpo124.jpg',
      detailImage:'../assets/images/portfolio/banpo124.jpg', imageAlt:'반포124주구 재건축 조감도',
      floorInfo:'지하4층 / 지상35층', floorAbove:35, floorBelow:4,
      grossFloorArea:'약 1,310,000㎡', floorAreaRatio:'249.9%',
      members:'약 3,200명', memberCount:3200,
      siteArea:'370,484㎡', buildingArea:'약 111,000㎡', constructor:'현대건설', client:'반포124주구재건축정비사업조합',
      phase:'관리처분계획 변경 추진 중', totalCost:'약 8조원 (추정)', proportionalRate:null,
      tasks:['공공관리 조합설립추진위원회 승인업무 자문','사업성분석업무 자문'],
      issues:['반포 핵심 입지 대규모 재건축 — 5,007세대','관리처분계획 변경 공개 2026.02.12 진행 중','현대건설 시공','사업시행인가 변경일 2024.09.03'] },
    { id:'pf3', name:'왕십리1구역 주택재개발 정비사업', type:'재개발', district:'성동구', status:'완료', year:'2016', scale:'1,702세대',
      role:'정비사업 자문',
      description:'서울 성동구 하왕십리동 339-67번지 일대 주택재개발 정비사업. 지상 25층 20동 1,702세대 규모이며 삼성물산·GS건설·대림산업·현대산업개발 4개사 컨소시엄이 시공한 대형 재개발 사업이다. 성동구 왕십리 권역의 도시정비를 선도한 사업으로, 당사는 사업 추진 전반의 절차 및 조합운영을 자문하였다.',
      featured:true,
      thumbnail:'../assets/images/portfolio/wangsimni1.jpg', featuredImage:'../assets/images/portfolio/wangsimni1.jpg',
      detailImage:'../assets/images/portfolio/wangsimni1.jpg', imageAlt:'왕십리1구역 주택재개발 조감도',
      floorInfo:'지하2층 / 지상25층', floorAbove:25, floorBelow:2,
      grossFloorArea:'약 420,000㎡', floorAreaRatio:'249.8%',
      members:'약 1,100명', memberCount:1100,
      siteArea:'약 168,000㎡', buildingArea:'약 42,000㎡', constructor:'삼성물산·GS건설·대림산업·현대산업개발 컨소시엄', client:'왕십리1구역주택재개발정비사업조합',
      phase:'준공 완료', totalCost:'약 8,000억원 (추정)', proportionalRate:null,
      tasks:['정비사업 추진 절차 자문','조합운영 지원 자문','사업시행 행정 절차 자문','관리처분계획 수립 자문','시공사 선정 자문','사업성 분석 자문'],
      issues:['성동구 하왕십리 일대 1,702세대 대규모 재개발','4개사 컨소시엄 시공','왕십리 뉴타운 권역 도시정비 선도 사업','사업 성공적 완료'] },
    { id:'pf4', name:'가락현대6차 가로주택정비사업', type:'소규모정비', district:'송파구', status:'진행중', year:'2023', scale:'191세대',
      role:'정비사업 자문',
      description:'서울 송파구 가락동 55번지 일대 가로주택정비사업. 지하 3층~지상 25층 2동 191세대 규모이며 현대엔지니어링이 시공을 맡고 있다. 총 사업비 1,017억원 규모로 2023년 11월 조합설립인가를 받아 본격 추진 중이다. 당사는 사업 추진 단계 전반의 절차 및 사업성을 자문하고 있다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/garak6.jpg', featuredImage:'../assets/images/portfolio/garak6.jpg',
      detailImage:'../assets/images/portfolio/garak6.jpg', imageAlt:'가락현대6차 가로주택정비사업 조감도',
      floorInfo:'지하3층 / 지상25층', floorAbove:25, floorBelow:3,
      grossFloorArea:'약 24,000㎡', floorAreaRatio:'249.9%',
      members:'약 120명', memberCount:120,
      siteArea:'약 8,000㎡', buildingArea:'약 2,800㎡', constructor:'현대엔지니어링', client:'가락현대6차가로주택정비사업조합',
      phase:'조합설립인가 (2023.11)', totalCost:'약 1,017억원', proportionalRate:null,
      tasks:['가로주택정비사업 사업성 분석 자문','조합설립 절차 자문','사업시행계획 인허가 자문','시공사 선정 자문','사업 추진 전략 자문'],
      issues:['조합설립인가 2023.11 완료','현대엔지니어링 시공 — 1,017억원 규모','2동 191세대 규모','가락동 소규모 가로주택정비사업'] },
    { id:'pf5', name:'미아3재정비촉진구역 주택재개발 정비사업', type:'재개발', district:'강북구', status:'진행중', year:'2024', scale:'1,037세대',
      role:'정비사업 자문',
      description:'서울 강북구 미아동 439번지 일대 57,553㎡ 부지의 재개발 정비사업. 1,037세대 규모이며 롯데건설이 시공을 맡고 있다. 조합설립인가(2015.01.13), 관리처분인가(2024.06.03)를 거쳐 2024년 11월 이주를 개시하였다. 당사는 사업시행 행정 절차 및 관리처분 단계 업무를 자문하였다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/redev1.jpg', featuredImage:'../assets/images/portfolio/redev1.jpg',
      detailImage:'../assets/images/portfolio/redev1.jpg', imageAlt:'미아3재정비촉진구역 재개발 현장',
      floorInfo:'지하3층 / 지상28층', floorAbove:28, floorBelow:3,
      grossFloorArea:'약 145,000㎡', floorAreaRatio:'249.9%',
      members:'약 700명', memberCount:700,
      siteArea:'57,553㎡', buildingArea:'약 17,300㎡', constructor:'롯데건설', client:'미아3재정비촉진구역주택재개발정비사업조합',
      phase:'이주 진행중 (2024.11~)', totalCost:'약 7,000억원 (추정)', proportionalRate:null,
      tasks:['사업시행 행정 절차 자문','관리처분계획 수립 자문','이주 계획 수립 자문','사업성 분석 자문'],
      issues:['관리처분인가 2024.06.03 완료','이주개시 2024.11.19','롯데건설 시공','강북구 미아동 57,553㎡ 규모'] },
    { id:'pf6', name:'면목1구역 재건축 정비사업', type:'재건축', district:'중랑구', status:'완료', year:'2020', scale:'131세대',
      role:'정비사업 자문',
      description:'서울 중랑구 면목동 520-19번지 일대 24,240㎡ 부지의 재건축 정비사업. 131세대 규모이며 한양이 시공을 맡았다. 준공인가(2019.11.27) 및 이전고시(2020.05.21)를 완료하며 사업이 성공적으로 마무리되었다. 당사는 준공 단계 및 이전등기 절차를 자문하였다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/myunmok1.jpg', featuredImage:'../assets/images/portfolio/myunmok1.jpg',
      detailImage:'../assets/images/portfolio/myunmok1.jpg', imageAlt:'면목1구역 재건축 완료 전경',
      floorInfo:'지하2층 / 지상20층', floorAbove:20, floorBelow:2,
      grossFloorArea:'약 30,000㎡', floorAreaRatio:'199.8%',
      members:'약 80명', memberCount:80,
      siteArea:'24,240㎡', buildingArea:'약 7,300㎡', constructor:'한양', client:'면목1구역재건축정비사업조합',
      phase:'이전고시 완료 (2020.05.21)', totalCost:'약 300억원 (추정)', proportionalRate:null,
      tasks:['준공 절차 자문','이전등기 절차 자문','조합 해산·정산 자문'],
      issues:['준공인가 2019.11.27','이전고시 2020.05.21 완료','한양 시공','중랑구 면목동 24,240㎡ 규모'] },
    { id:'pf7', name:'당산현대2차 소규모재건축 정비사업', type:'소규모정비', district:'영등포구', status:'진행중', year:'2026', scale:'145세대',
      role:'정비사업 자문',
      description:'서울 영등포구 당산동4가 92번지 일대 소규모재건축 정비사업. 2동 145세대 규모로 현재 관리처분인가 절차를 진행하고 있다. 당산동 역세권 입지의 프리미엄을 바탕으로 사업성이 양호하다. 당사는 추진위원회 단계부터 관리처분 절차 전반을 자문하고 있다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/dangsan2.jpg', featuredImage:'../assets/images/portfolio/dangsan2.jpg',
      detailImage:'../assets/images/portfolio/dangsan2.jpg', imageAlt:'당산현대2차 소규모재건축 조감도',
      floorInfo:'지하2층 / 지상20층', floorAbove:20, floorBelow:2,
      grossFloorArea:'약 18,000㎡', floorAreaRatio:'219.8%',
      members:'약 95명', memberCount:95,
      siteArea:'약 7,000㎡', buildingArea:'약 2,100㎡', constructor:'미정', client:'당산현대2차소규모재건축조합',
      phase:'관리처분인가 진행중', totalCost:'약 350억원 (추정)', proportionalRate:null,
      tasks:['소규모재건축 사업성 분석 자문','조합설립 절차 자문','사업시행계획 인허가 자문','관리처분계획 수립 자문','시공사 선정 자문'],
      issues:['관리처분인가 진행중','당산동 역세권 프리미엄 입지','소규모재건축 특례 적용','2동 145세대 규모'] },
    { id:'pf8', name:'미아1구역 가로주택정비사업', type:'소규모정비', district:'강북구', status:'진행중', year:'2021', scale:'79세대',
      role:'정비사업 자문',
      description:'서울 강북구 미아동 833-2번지 일대 6,439㎡ 부지의 가로주택정비사업. 79세대 규모이며 한양이 시공을 맡고 있다. 2021년 6월 조합설립인가를 받아 사업을 진행하고 있다. 당사는 조합설립 이후 사업추진 절차 및 인허가 업무를 자문하고 있다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/redev2.jpg', featuredImage:'../assets/images/portfolio/redev2.jpg',
      detailImage:'../assets/images/portfolio/redev2.jpg', imageAlt:'미아1구역 가로주택정비사업 현장',
      floorInfo:'지하1층 / 지상15층', floorAbove:15, floorBelow:1,
      grossFloorArea:'약 8,500㎡', floorAreaRatio:'199.8%',
      members:'약 50명', memberCount:50,
      siteArea:'6,439㎡', buildingArea:'약 1,700㎡', constructor:'한양', client:'미아1구역가로주택정비사업조합',
      phase:'사업시행 단계', totalCost:'약 180억원 (추정)', proportionalRate:null,
      tasks:['가로주택정비사업 사업성 분석 자문','조합설립 절차 자문','사업시행 인허가 자문','사업 추진 전략 자문'],
      issues:['조합설립인가 2021.06.02 완료','한양 시공','강북구 미아동 6,439㎡ 규모','79세대 소규모 가로주택정비'] },
    { id:'pf9', name:'방배대우 가로주택정비사업', type:'소규모정비', district:'서초구', status:'진행중', year:'2023', scale:'136세대',
      role:'정비사업 자문',
      description:'서울 서초구 방배동 562-1번지 일대 가로주택정비사업. 3동 20층 136세대 규모로 조합설립인가(2022.09.21), 조합설립변경인가(2023.04.03)를 완료하고 사업을 추진 중이다. 방배동 프리미엄 주거 입지에 위치하여 사업성이 우수하다. 당사는 조합설립 단계부터 사업시행 인허가 절차를 자문하고 있다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/bangbae_daewo.jpg', featuredImage:'../assets/images/portfolio/bangbae_daewo.jpg',
      detailImage:'../assets/images/portfolio/bangbae_daewo.jpg', imageAlt:'방배대우 가로주택정비사업 조감도',
      floorInfo:'지하2층 / 지상20층', floorAbove:20, floorBelow:2,
      grossFloorArea:'약 16,500㎡', floorAreaRatio:'219.8%',
      members:'약 85명', memberCount:85,
      siteArea:'약 6,200㎡', buildingArea:'약 1,860㎡', constructor:'미정', client:'방배대우가로주택정비사업조합',
      phase:'사업시행인가 추진 중', totalCost:'약 300억원 (추정)', proportionalRate:null,
      tasks:['가로주택정비사업 사업성 분석 자문','조합설립 절차 자문','조합설립변경인가 절차 자문','사업시행 인허가 자문','시공사 선정 자문'],
      issues:['조합설립인가 2022.09.21','조합설립변경인가 2023.04.03','방배동 서초구 프리미엄 입지','3동 136세대 가로주택정비'] },
    { id:'pf10', name:'공덕현대 소규모재건축 정비사업', type:'소규모정비', district:'마포구', status:'진행중', year:'2026', scale:'232세대',
      role:'정비사업 자문',
      description:'서울 마포구 공덕동 370-9번지 일대 소규모재건축 정비사업. 2동 20층 232세대 규모이며 한화건설이 시공을 맡을 예정이다. 현재 사업시행계획인가를 추진하고 있다. 공덕역(5·6호선·경의중앙선·공항철도) 쿼드러플 역세권의 탁월한 입지를 보유한 사업지로, 당사는 사업추진 절차 및 사업성을 자문하고 있다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/gongdeok.png', featuredImage:'../assets/images/portfolio/gongdeok.png',
      detailImage:'../assets/images/portfolio/gongdeok.png', imageAlt:'공덕현대 소규모재건축 조감도',
      floorInfo:'지하3층 / 지상20층', floorAbove:20, floorBelow:3,
      grossFloorArea:'약 27,000㎡', floorAreaRatio:'219.8%',
      members:'약 140명', memberCount:140,
      siteArea:'약 10,000㎡', buildingArea:'약 3,000㎡', constructor:'한화건설', client:'공덕현대소규모재건축조합',
      phase:'사업시행계획인가 추진 중', totalCost:'약 600억원 (추정)', proportionalRate:null,
      tasks:['소규모재건축 사업성 분석 자문','추진 절차 자문','사업시행계획 인허가 자문','시공사 선정 자문','사업 추진 전략 자문'],
      issues:['공덕역 쿼드러플 역세권 (5·6호선·경의중앙·공항철도)','한화건설 시공 예정','사업시행계획인가 진행 중','2동 232세대 규모'] },
    { id:'pf11', name:'휘경4구역 주택재개발 정비사업', type:'재개발', district:'동대문구', status:'완료', year:'2015', scale:'451세대',
      role:'정비사업 자문',
      description:'서울 동대문구 휘경동 39-60번지 일대 주택재개발 정비사업. 451세대 규모로 사업을 성공적으로 완료하였다. 당사는 사업추진 단계의 행정 절차 및 조합운영 전반을 자문하였다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/hwikyung4.jpg', featuredImage:'../assets/images/portfolio/hwikyung4.jpg',
      detailImage:'../assets/images/portfolio/hwikyung4.jpg', imageAlt:'휘경4구역 주택재개발 완료 전경',
      floorInfo:'지하2층 / 지상20층', floorAbove:20, floorBelow:2,
      grossFloorArea:'약 55,000㎡', floorAreaRatio:'219.8%',
      members:'약 280명', memberCount:280,
      siteArea:'약 22,000㎡', buildingArea:'약 6,600㎡', constructor:'미정', client:'휘경4구역주택재개발정비사업조합',
      phase:'준공 완료', totalCost:'약 1,500억원 (추정)', proportionalRate:null,
      tasks:['사업시행 행정 절차 자문','조합운영 지원 자문','관리처분계획 수립 자문','준공 절차 자문'],
      issues:['동대문구 휘경동 451세대 재개발','사업 성공적 완료','이문·휘경 뉴타운 권역 정비 기여'] },
    { id:'pf12', name:'행당4구역 주택재개발 정비사업', type:'재개발', district:'성동구', status:'완료', year:'2017', scale:'465세대',
      role:'정비사업 자문',
      description:'서울 성동구 행당동(행당2동) 338-6번지 일대 주택재개발 정비사업. 7동 465세대 규모로 2017년 12월 이전고시(2017.12.08)를 완료하며 사업을 마무리하였다. 당사는 관리처분 단계 및 이주·철거·준공 절차를 자문하였다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/haengdang4.jpg', featuredImage:'../assets/images/portfolio/haengdang4.jpg',
      detailImage:'../assets/images/portfolio/haengdang4.jpg', imageAlt:'행당4구역 주택재개발 완료 전경',
      floorInfo:'지하2층 / 지상25층', floorAbove:25, floorBelow:2,
      grossFloorArea:'약 57,000㎡', floorAreaRatio:'219.8%',
      members:'약 290명', memberCount:290,
      siteArea:'약 23,000㎡', buildingArea:'약 6,900㎡', constructor:'미정', client:'행당4구역주택재개발정비사업조합',
      phase:'이전고시 완료 (2017.12.08)', totalCost:'약 1,600억원 (추정)', proportionalRate:null,
      tasks:['관리처분계획 수립 자문','이주·철거 절차 자문','준공 절차 자문','이전고시 업무 자문'],
      issues:['이전고시 2017.12.08 완료','7동 465세대 재개발','성동구 행당동 권역 도시정비 기여'] },
    { id:'pf13', name:'옥수13구역 주택재개발 정비사업', type:'재개발', district:'성동구', status:'완료', year:'2014', scale:'미상',
      role:'정비사업 자문',
      description:'서울 성동구 옥수동 526번지 일대 주택재개발 정비사업. 성동구 옥수동 한강변 일대를 정비하여 도시환경을 개선한 사업으로 성공적으로 완료되었다. 당사는 사업추진 단계의 행정 절차 및 인허가 업무를 자문하였다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/oksu13.jpg', featuredImage:'../assets/images/portfolio/oksu13.jpg',
      detailImage:'../assets/images/portfolio/oksu13.jpg', imageAlt:'옥수13구역 주택재개발 완료 전경',
      floorInfo:'지하2층 / 지상25층', floorAbove:25, floorBelow:2,
      grossFloorArea:'미상', floorAreaRatio:'219.8%',
      members:'미상', memberCount:0,
      siteArea:'미상', buildingArea:'미상', constructor:'미정', client:'옥수13구역주택재개발정비사업조합',
      phase:'준공 완료', totalCost:'미상', proportionalRate:null,
      tasks:['사업시행 행정 절차 자문','인허가 업무 자문','준공 절차 자문'],
      issues:['성동구 옥수동 526 재개발','한강변 도시정비 사업','사업 성공적 완료'] },
    { id:'pf14', name:'마장1구역 주택재개발 정비사업', type:'재개발', district:'성동구', status:'진행중', year:'2026', scale:'262세대',
      role:'정비사업 추진 자문',
      description:'서울 성동구 마장동 382번지 일대 17,854㎡ 부지의 주택재개발 정비사업. 6동 24층 262세대 규모로 2026년 3월 조합설립추진위원회를 구성(2026.03.19)하여 사업을 개시하였다. 당사는 추진위원회 구성 단계부터 사업 초기 절차 전반을 자문하고 있다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/majang1.jpg', featuredImage:'../assets/images/portfolio/majang1.jpg',
      detailImage:'../assets/images/portfolio/majang1.jpg', imageAlt:'마장1구역 주택재개발 계획도',
      floorInfo:'지하2층 / 지상24층', floorAbove:24, floorBelow:2,
      grossFloorArea:'약 32,000㎡', floorAreaRatio:'219.8%',
      members:'미정', memberCount:0,
      siteArea:'17,854㎡', buildingArea:'약 5,400㎡', constructor:'미정', client:'마장1구역주택재개발정비사업추진위원회',
      phase:'추진위원회 구성 (2026.03.19)', totalCost:'약 700억원 (추정)', proportionalRate:null,
      tasks:['정비사업 타당성 검토 자문','추진위원회 구성 절차 자문','사업성 분석 자문','정비계획 수립 준비 자문'],
      issues:['추진위원회 구성 2026.03.19 완료','성동구 마장동 17,854㎡ 규모','6동 262세대 재개발','사업 초기 단계'] },
    { id:'pf15', name:'효창5구역 주택재개발 정비사업', type:'재개발', district:'용산구', status:'완료', year:'2015', scale:'미상',
      role:'정비사업 자문',
      description:'서울 용산구 효창동 일대 주택재개발 정비사업. 용산구 효창동 노후 주거지를 정비하여 도시환경을 개선한 사업으로 성공적으로 완료되었다. 당사는 사업 추진 단계의 행정 절차 및 조합운영을 자문하였다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/hyochang5.jpg', featuredImage:'../assets/images/portfolio/hyochang5.jpg',
      detailImage:'../assets/images/portfolio/hyochang5.jpg', imageAlt:'효창5구역 주택재개발 완료 전경',
      floorInfo:'지하2층 / 지상20층', floorAbove:20, floorBelow:2,
      grossFloorArea:'미상', floorAreaRatio:'219.8%',
      members:'미상', memberCount:0,
      siteArea:'미상', buildingArea:'미상', constructor:'미정', client:'효창5구역주택재개발정비사업조합',
      phase:'준공 완료', totalCost:'미상', proportionalRate:null,
      tasks:['사업시행 행정 절차 자문','조합운영 지원 자문','준공 절차 자문'],
      issues:['용산구 효창동 재개발','도시정비 사업 완료','효창공원 인근 입지'] },
    { id:'pf16', name:'용두4구역 주택재개발 정비사업', type:'재개발', district:'동대문구', status:'진행중', year:'2026', scale:'약 1,000세대',
      role:'정비사업 자문',
      description:'서울 동대문구 용두동 일대 주택재개발 정비사업. 약 1,000세대 규모로 추진 중이며 동대문구 용두동 노후 주거지의 광역 정비를 목표로 한다. 당사는 사업 추진 단계의 절차 및 사업성 분석을 자문하고 있다.',
      featured:false,
      thumbnail:'../assets/images/portfolio/yongdu4.jpg', featuredImage:'../assets/images/portfolio/yongdu4.jpg',
      detailImage:'../assets/images/portfolio/yongdu4.jpg', imageAlt:'용두4구역 주택재개발 조감도',
      floorInfo:'지하3층 / 지상25층', floorAbove:25, floorBelow:3,
      grossFloorArea:'약 123,000㎡', floorAreaRatio:'249.8%',
      members:'미정', memberCount:0,
      siteArea:'미상', buildingArea:'미상', constructor:'미정', client:'용두4구역주택재개발정비사업조합',
      phase:'추진 중', totalCost:'약 3,000억원 (추정)', proportionalRate:null,
      tasks:['정비사업 타당성 검토 자문','사업성 분석 자문','인허가 절차 자문','사업 추진 전략 자문'],
      issues:['동대문구 용두동 약 1,000세대 재개발','사업 추진 중','용두동 노후 주거지 도시정비'] }
  ],

"""

START_MARKER = '  /* ──────────────────────────── 업무실적'
END_MARKER = '  /* ──────────────────────────── 자료실'

with open(FILE_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

start_idx = content.find(START_MARKER)
end_idx = content.find(END_MARKER)

if start_idx == -1:
    print("ERROR: START_MARKER not found")
    exit(1)
if end_idx == -1:
    print("ERROR: END_MARKER not found")
    exit(1)

print(f"Found portfolio section: chars {start_idx} to {end_idx}")
print(f"Section length: {end_idx - start_idx} chars")

new_content = content[:start_idx] + NEW_PORTFOLIO + content[end_idx:]

with open(FILE_PATH, 'w', encoding='utf-8') as f:
    f.write(new_content)

print("✅ mock-data.js portfolio section replaced successfully!")
print(f"New file size: {len(new_content)} chars")
